#!/bin/sh
#License: CC0

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ] || [ -f /etc/centos-release ]; then
	echo "NOTE: you must first reboot if you haven't since last installing a kernel";
	echo "Installing updated microcode, to restore: dnf reinstall linux-firmware";
	cp -fv /usr/lib/firmware/amd-ucode-real/microcode_amd_fam*.bin /usr/lib/firmware/amd-ucode/;
	cp -fv /usr/lib/firmware/intel-ucode-real/* /usr/lib/firmware/intel-ucode/;
	echo "Invoking dracut";
	dracut -f;
	echo "Please reboot to enjoy new microcode :)";
else
	echo "Currently only Fedora and CentOS are supported";
fi;
