.\" this is a comment`
.TH MICROCODE_CTL "8" "19 January 2006" "microcode_ctl"
.SH NAME
microcode_ctl \- microcode utility for Intel IA32 processors
.SH SYNOPSIS
.B microcode_ctl
[\fI\-h\fR] [\fI\-u\fR [\fI\-q\fR]] [\fI\-Q\fR] [\fI\-f microcode\fR]
.br
.SH DESCRIPTION
." Add any additional description here
.PP
The microcode_ctl utility is a companion to the IA32 microcode driver written
by Tigran Aivazian <tigran@veritas.com>. The utility has two uses:
.br
.PP
\fBa)\fR it decodes and sends new microcode to the kernel driver to be
uploaded to Intel IA32 processors. (Pentium Pro, PII, Celeron, PIII,
Xeon, Pentium 4 etc)
.PP
\fBb)\fR it signals the kernel driver to release the buffers containing the
copy of microcode data actually applied to given CPU, linear array of 2048
bytes per CPU, see struct microcode in include/asm/processor.h for
information on the layout of chunks buffers may hold
.br
.PP
The microcode update is volatile and needs to be uploaded on each system
boot i.e. it doesn't reflash your cpu permanently, reboot and it reverts
back to the old microcode.
.br
.TP
\fB\-h\fR
display usage and exit
.TP
\fB\-u\fR
upload microcode (from default filename)
.TP
\fB\-f\fR
upload microcode from named Intel formatted file
.TP
\fB\-q\fR
run silently when successful
.TP
\fB\-Q\fR
run silently even on failure
.PD
.SH EXAMPLE
.TP
microcode_ctl -u
Upload microcode using defaults
.SH FILES
.TP
/etc/microcode.dat
The default microcode location
.PD
.SH AUTHOR
Microcode utility written by Simon Trimmer
.br
Linux Kernel driver written by Tigran Aivazian.
.SH "REPORTING BUGS"
Report bugs to either Simon Trimmer <simon@urbanmyth.org> or
Tigran Aivazian <tigran@veritas.com>
.SH COPYRIGHT
Copyright \(co 2000 VERITAS Software
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SPECIAL THANKS"
Thanks to the Intel Corporation, for supplying microcode update data and
publishing the specifications that enabled us to write microcode driver for
Linux.
.br 
.SH "SEE ALSO"
The brave are recommended to view the driver source code located in the
Linux Kernel source tree in arch/i386/kernel/microcode.c
.PP
Visit http://www.urbanmyth.org/microcode/ for more information
and microcode updates.
